package com.example.ui.localization

import androidx.compose.ui.unit.LayoutDirection

object Localization {

    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "Zellige Stays",
            "lang_select" to "Select Your Language",
            "lang_select_sub" to "Experience the luxurious Moroccan stays in your preferred language.",
            "splash_welcome" to "Zellige Stays",
            "splash_sub" to "Luxury Moroccan Tourism & Stays",
            "discover" to "Discover Moroccan Magic",
            "search_placeholder" to "Search by city (Marrakech, Rabat...)",
            "categories" to "Categories",
            "popular_stays" to "Popular Accommodations",
            "featured_destinations" to "Featured Destinations",
            "special_offers" to "Special Stays",
            "all_cities" to "Explore All Cities",
            "price_per_night" to "/ night",
            "rating" to "Rating",
            "amenities" to "Amenities & Services",
            "location" to "Location",
            "book_now" to "Book Now",
            "favorites" to "Saved Stays",
            "reservations" to "My Reservations",
            "profile" to "My Profile",
            "search_screen" to "Search",
            "filter" to "Filters",
            "price_range" to "Price Range Limit",
            "property_type" to "Property Type",
            "any" to "Any",
            "rating_min" to "Minimum Rating",
            "apply_filters" to "Apply Filters",
            "clear_all" to "Clear All",
            "login" to "Log In",
            "register" to "Register",
            "email" to "Email Address",
            "password" to "Password",
            "full_name" to "Full Name",
            "phone" to "Phone Number",
            "no_account" to "Don't have an account? Register",
            "have_account" to "Already have an account? Login",
            "check_in" to "Check-In Date",
            "check_out" to "Check-Out Date",
            "guests" to "Number of Guests",
            "total_price" to "Total Price",
            "confirm_booking" to "Confirm Reservation",
            "booking_success" to "Reservation Successful!",
            "booking_success_desc" to "Your luxury stay has been reserved. You can view it under My Reservations.",
            "upcoming" to "Upcoming",
            "completed" to "Completed",
            "no_reservations" to "No reservations made yet.",
            "no_favorites" to "Your favorites list is empty.",
            "logged_in_as" to "Logged in as",
            "become_host" to "Become a Host",
            "become_host_desc" to "Share your majestic Moroccan space with travelers from around the world.",
            "host_dashboard" to "Host Portal",
            "admin_dashboard" to "Admin Command Center",
            "logout" to "Log Out",
            "stats" to "Performance Analytics",
            "total_properties" to "Total Properties",
            "total_bookings" to "Stays Booked",
            "sub_status" to "Subscription Status",
            "free_trial" to "2-Month Free Trial Active",
            "active" to "Active",
            "expired" to "Expired - Subscription Required",
            "renew_sub" to "Activate Gold Annual Subscription",
            "add_property" to "List a New Stay",
            "add_title" to "Property Title",
            "add_desc" to "Rich Story Writing (Description)",
            "add_city" to "Select City",
            "add_address" to "Physical Address",
            "add_price" to "Price Per Night (USD)",
            "add_type" to "Stay Class (Type)",
            "add_amenities" to "Key Amenities (comma separated)",
            "add_images" to "Media Photo URLs (comma separated)",
            "submit_property" to "Publish Property",
            "manage_properties" to "Manage My Stays",
            "edit" to "Edit",
            "delete" to "Delete",
            "analytics" to "Platform Analytics",
            "user_mgt" to "User Accounts Management",
            "property_mgt" to "Accommodations Management",
            "sub_mgt" to "Host Subscriptions Management",
            "admin_title" to "Zellige Admin Console",
            "search_btn" to "Find Stays",
            "visitors_can" to "Sign in to access secure bookings & host features.",
            "moroccan_star" to "Proudly Celebrating Moroccan Hospitality",
            "mandatory_field" to "All fields are required to proceed."
        ),
        "ar" to mapOf(
            "app_title" to "زليج ستيز",
            "lang_select" to "اختر لغتك المفضلة",
            "lang_select_sub" to "استمتع بتجربة الإقامة المغربية الفاخرة باللغة التي تفضلها.",
            "splash_welcome" to "زليج ستيز",
            "splash_sub" to "السياحة والإقامة المغربية الفاخرة",
            "discover" to "اكتشف سحر المغرب",
            "search_placeholder" to "ابحث عن مدينة (مراكش، الرباط...)",
            "categories" to "الفئات الإرشادية",
            "popular_stays" to "الإقامات الأكثر شعبية",
            "featured_destinations" to "الوجهات المميزة",
            "special_offers" to "عروض خاصة فاخرة",
            "all_cities" to "استكشف كل المدن",
            "price_per_night" to "/ ليلة",
            "rating" to "التقييم",
            "amenities" to "المرافق والخدمات المتاحة",
            "location" to "الموقع والاتجاهات",
            "book_now" to "احجز ملاذك الآن",
            "favorites" to "الإقامات المفضلة",
            "reservations" to "حجوزاتي الفاخرة",
            "profile" to "حسابي الشخصي",
            "search_screen" to "البحث المتقدم",
            "filter" to "تصفية النتائج",
            "price_range" to "الحد الأقصى للسعر",
            "property_type" to "نوع العقار الإقامة",
            "any" to "أي نوع",
            "rating_min" to "الحد الأدنى للتقييم",
            "apply_filters" to "تطبيق خيارات التصفية",
            "clear_all" to "إعادة تعيين",
            "login" to "تسجيل الدخول",
            "register" to "إنشاء حساب جديد",
            "email" to "البريد الإلكتروني",
            "password" to "كلمة المرور الحامية",
            "full_name" to "الاسم الكامل",
            "phone" to "رقم الهاتف والرمز",
            "no_account" to "ليس لديك حساب؟ سجل معنا الآن",
            "have_account" to "لديك حساب بالفعل؟ ابدأ بالدخول",
            "check_in" to "تاريخ تسجيل الدخول",
            "check_out" to "تاريخ مغادرة الملاذ",
            "guests" to "عدد الضيوف الأكارم",
            "total_price" to "إجمالي التكلفة الإجمالية",
            "confirm_booking" to "تأكيد الحجز النهائي",
            "booking_success" to "تم الحجز بنجاح تام!",
            "booking_success_desc" to "لقد تم تأمين ملاذك الفاخر بنجاح. يمكنك مراجعة التفاصيل في شاشة حجوزاتي.",
            "upcoming" to "حجوزات قادمة",
            "completed" to "حجوزات مكتملة",
            "no_reservations" to "لم تقم بأي حجوزات حتى الآن.",
            "no_favorites" to "قائمة مفضلاتك فارغة حالياً.",
            "logged_in_as" to "مسجل الدخول باسم",
            "become_host" to "كن مضيفاً معنا",
            "become_host_desc" to "شارك روعة عقارك المغربي الأصيل مع المسافرين من شتى أنحاء العالم والاستفادة من عوائده.",
            "host_dashboard" to "بوابة المضيف",
            "admin_dashboard" to "لوحة التحكم للمدير",
            "logout" to "تسجيل الخروج الآمن",
            "stats" to "الإحصاءات والتحليلات البيانية",
            "total_properties" to "إجمالي العقارات المدرجة",
            "total_bookings" to "إجمالي الحجوزات الناشطة",
            "sub_status" to "حالة الاشتراك والتفعيل",
            "free_trial" to "تحت التجربة المجانية (شهرين)",
            "active" to "نشط ومتاح",
            "expired" to "منتهي الصلاحية - مطلوب الدفع",
            "renew_sub" to "تفعيل الاشتراك الذهبي السنوي",
            "add_property" to "إدراج ملاذ جديد",
            "add_title" to "عنوان العقار المميز",
            "add_desc" to "الوصف التفصيلي الجذاب للملاذ",
            "add_city" to "اختر المدينة المغربية",
            "add_address" to "العنوان الجغرافي الدقيق",
            "add_price" to "السعر لليلة الواحدة (بالدولار)",
            "add_type" to "تصنيف العقار لإقامة",
            "add_amenities" to "المرافق الأساسية (مفصولة بفاصلة)",
            "add_images" to "روابط صور المعرض (مفصولة بفاصلة)",
            "submit_property" to "نشر الملاذ بالمنصة",
            "manage_properties" to "إدارة عقاراتي وإقاماتي",
            "edit" to "تعديل",
            "delete" to "حذف",
            "analytics" to "تحليلات المنصة الشاملة",
            "user_mgt" to "إدارة المستخدمين وحساباتهم",
            "property_mgt" to "إدارة العقارات والتحقق",
            "sub_mgt" to "الاشتراكات والمدفوعات",
            "admin_title" to "بوابة الإدارة المركزية",
            "search_btn" to "ابحث عن إقامة",
            "visitors_can" to "الرجاء تسجيل الدخول للوصول للحجوزات والخصائص الإضافية.",
            "moroccan_star" to "تجسيد فخور لروح الضيافة المغربية العريقة",
            "mandatory_field" to "جميع حقول البيانات مطلوبة للمتابعة."
        ),
        "fr" to mapOf(
            "app_title" to "Zellige Stays",
            "lang_select" to "Sélectionnez Votre Langue",
            "lang_select_sub" to "Découvrez des séjours marocains luxueux dans votre langue préférée.",
            "splash_welcome" to "Zellige Stays",
            "splash_sub" to "Tourisme & Séjours Marocains de Luxe",
            "discover" to "Découvrez la Magie du Maroc",
            "search_placeholder" to "Rechercher par ville (Marrakech, Rabat...)",
            "categories" to "Catégories",
            "popular_stays" to "Hébergements Populaires",
            "featured_destinations" to "Destinations Vedettes",
            "special_offers" to "Séjours Spéciaux",
            "all_cities" to "Explorer Toutes les Villes",
            "price_per_night" to "/ nuit",
            "rating" to "Évaluation",
            "amenities" to "Équipements & Services",
            "location" to "Emplacement",
            "book_now" to "Réserver Maintenant",
            "favorites" to "Favoris",
            "reservations" to "Mes Réservations",
            "profile" to "Mon Profil",
            "search_screen" to "Recherche",
            "filter" to "Filtres",
            "price_range" to "Limite de Prix",
            "property_type" to "Type de Propriété",
            "any" to "Tous",
            "rating_min" to "Note Minimale",
            "apply_filters" to "Appliquer les Filtres",
            "clear_all" to "Effacer Tout",
            "login" to "Se Connecter",
            "register" to "S'inscrire",
            "email" to "Adresse Email",
            "password" to "Mot de Passe",
            "full_name" to "Nom Complet",
            "phone" to "Numéro de Téléphone",
            "no_account" to "Pas de compte? S'enregistrer",
            "have_account" to "Déjà un compte? Se connecter",
            "check_in" to "Date d'arrivée",
            "check_out" to "Date de départ",
            "guests" to "Nombre d'invités",
            "total_price" to "Prix Total",
            "confirm_booking" to "Confirmer la Réservation",
            "booking_success" to "Réservation Réussie!",
            "booking_success_desc" to "Votre séjour de luxe a été réservé. Retrouvez-le dans Mes Réservations.",
            "upcoming" to "À venir",
            "completed" to "Terminé",
            "no_reservations" to "Aucune réservation pour l'instant.",
            "no_favorites" to "Votre liste de favoris est vide.",
            "logged_in_as" to "Connecté en tant que",
            "become_host" to "Devenir Hôte",
            "become_host_desc" to "Partagez votre majestueux espace marocain avec les voyageurs du monde entier.",
            "host_dashboard" to "Portail Hôte",
            "admin_dashboard" to "Centre de Contrôle Admin",
            "logout" to "Se Déconnecter",
            "stats" to "Analyses de Performance",
            "total_properties" to "Total des Propriétés",
            "total_bookings" to "Séjours Réservés",
            "sub_status" to "Statut d'Abonnement",
            "free_trial" to "Essai Gratuit de 2 Mois Actif",
            "active" to "Actif",
            "expired" to "Expiré - Mission Requise",
            "renew_sub" to "Activer l'Abonnement Annuel Or",
            "add_property" to "Publier un Hébergement",
            "add_title" to "Titre de l'hébergement",
            "add_desc" to "Description de l'hébergement (Riche conte)",
            "add_city" to "Sélectionner la Ville",
            "add_address" to "Adresse Physique",
            "add_price" to "Prix par nuit (USD)",
            "add_type" to "Type de Séjour",
            "add_amenities" to "Équipements (séparés par une virgule)",
            "add_images" to "URLs des Photos (séparées par une virgule)",
            "submit_property" to "Publier Hôte",
            "manage_properties" to "Gérer mes propriétés",
            "edit" to "Modifier",
            "delete" to "Supprimer",
            "analytics" to "Statistiques Globales",
            "user_mgt" to "Gestion des Comptes Utilisateurs",
            "property_mgt" to "Gestion des Hébergements",
            "sub_mgt" to "Gestion des Abonnements Hôtes",
            "admin_title" to "Console Admin Zellige",
            "search_btn" to "Trouver un séjour",
            "visitors_can" to "Connectez-vous pour réserver des séjours et gérer vos espaces.",
            "moroccan_star" to "Célébrer fièrement l'Hospitalité Marocaine",
            "mandatory_field" to "Tous les champs sont requis pour continuer."
        ),
        "es" to mapOf(
            "app_title" to "Zellige Stays",
            "lang_select" to "Selecciona Tu Idioma",
            "lang_select_sub" to "Viva la experiencia del lujo marroquí en el idioma que usted prefiera.",
            "splash_welcome" to "Zellige Stays",
            "splash_sub" to "Turismo y Alojamientos Marroquíes de Lujo",
            "discover" to "Descubra la Magia de Marruecos",
            "search_placeholder" to "Buscar por ciudad (Marrakech, Rabat...)",
            "categories" to "Categorías",
            "popular_stays" to "Alojamientos Populares",
            "featured_destinations" to "Destinos Destacados",
            "special_offers" to "Atracciones Especiales",
            "all_cities" to "Explorar Todas las Ciudades",
            "price_per_night" to "/ noche",
            "rating" to "Clasificación",
            "amenities" to "Servicios e Instalaciones",
            "location" to "Ubicación",
            "book_now" to "Reservar Ahora",
            "favorites" to "Alojamientos Guardados",
            "reservations" to "Mis Reservas",
            "profile" to "Mi Perfil",
            "search_screen" to "Búsqueda Avanzada",
            "filter" to "Filtros",
            "price_range" to "Límite de precio",
            "property_type" to "Tipo de Propiedad",
            "any" to "Cualquiera",
            "rating_min" to "Calificación Mínima",
            "apply_filters" to "Aplicar Filtros",
            "clear_all" to "Limpiar Todo",
            "login" to "Iniciar Sesión",
            "register" to "Registrarse",
            "email" to "Correo Electrónico",
            "password" to "Contraseña",
            "full_name" to "Nombre Completo",
            "phone" to "Número de Teléfono",
            "no_account" to "¿No tiene una cuenta? Regístrese",
            "have_account" to "¿Ya tiene una cuenta? Inicie Sesión",
            "check_in" to "Fecha de Entrada",
            "check_out" to "Fecha de Salida",
            "guests" to "Número de Huéspedes",
            "total_price" to "Precio Total",
            "confirm_booking" to "Confirmar Reserva",
            "booking_success" to "¡Reserva Realizada con Éxito!",
            "booking_success_desc" to "Su estancia de lujo ha sido reservada. Puede verla en Mis Reservas.",
            "upcoming" to "Próximas",
            "completed" to "Completadas",
            "no_reservations" to "Aún no ha realizado ninguna reserva.",
            "no_favorites" to "Su lista de favoritos está vacía.",
            "logged_in_as" to "Sesión iniciada como",
            "become_host" to "Convertirse en Anfitrión",
            "become_host_desc" to "Comparta su majestuoso espacio marroquí con viajeros de todo el mundo.",
            "host_dashboard" to "Portal de Anfitrión",
            "admin_dashboard" to "Panel de Administración",
            "logout" to "Cerrar Sesión",
            "stats" to "Estadísticas de Rendimiento",
            "total_properties" to "Propiedades Totales",
            "total_bookings" to "Reservas Registradas",
            "sub_status" to "Estado de Suscripción",
            "free_trial" to "Prueba Gratuita de 2 Meses Activa",
            "active" to "Activo",
            "expired" to "Expirado - Pago Requerido",
            "renew_sub" to "Activar Suscripción Anual Oro",
            "add_property" to "Anunciar Nueva Estancia",
            "add_title" to "Título de la Propiedad",
            "add_desc" to "Descripción Detallada (Estilo Relato)",
            "add_city" to "Seleccionar Ciudad",
            "add_address" to "Dirección Física",
            "add_price" to "Precio por Noche (USD)",
            "add_type" to "Tipo de Alojamiento",
            "add_amenities" to "Instalaciones Clave (separadas por coma)",
            "add_images" to "URLs de las fotos (separadas por coma)",
            "submit_property" to "Publicar Propiedad",
            "manage_properties" to "Administrar mis propiedades",
            "edit" to "Editar",
            "delete" to "Eliminar",
            "analytics" to "Estadísticas Globales",
            "user_mgt" to "Gestión de Cuentas de Usuario",
            "property_mgt" to "Gestión de Alojamientos",
            "sub_mgt" to "Gestión de Suscripciones",
            "admin_title" to "Panel de Control Zellige",
            "search_btn" to "Buscar Alojamientos",
            "visitors_can" to "Inicie sesión para acceder a reservas seguras y de anfitrión.",
            "moroccan_star" to "Celebrando con orgullo el hospedaje marroquí",
            "mandatory_field" to "Todos los campos son obligatorios para proceder."
        )
    )

    fun get(key: String, lang: String): String {
        // Fallback sequentially to english, then the key itself
        val dict = translations[lang] ?: translations["en"] ?: return key
        return dict[key] ?: translations["en"]?.get(key) ?: key
    }

    fun getLayoutDirection(lang: String): LayoutDirection {
        return if (lang == "ar") LayoutDirection.Rtl else LayoutDirection.Ltr
    }
}
